import { useEffect, useMemo, useState } from "react";
import { supabase } from "../services/supabase";

type Media={id:string;storage_path:string;filename:string;alt_text:string|null;width:number|null;height:number|null;mime_type:string|null;file_size:number|null;created_at:string;product_images:{id:string;product_id:string;products:{name:string;internal_reference:string|null}|null}[]};

export default function AdminMedia(){
 const [items,setItems]=useState<Media[]>([]),[homepageMedia,setHomepageMedia]=useState<Set<string>>(new Set()),[error,setError]=useState(""),[saving,setSaving]=useState<string|null>(null),[query,setQuery]=useState("");
 async function load(){if(!supabase)return;setError("");const [mediaResult,homeResult]=await Promise.all([supabase.from("media").select("id,storage_path,filename,alt_text,width,height,mime_type,file_size,created_at,product_images(id,product_id,products(name,internal_reference))").order("created_at",{ascending:false}),supabase.from("homepage_carousel").select("media_id")]);if(mediaResult.error){setError(mediaResult.error.message);return}if(homeResult.error){setError(homeResult.error.message);return}setItems((mediaResult.data??[]) as unknown as Media[]);setHomepageMedia(new Set((homeResult.data??[]).map((x:any)=>x.media_id)))}
 useEffect(()=>{load()},[]);
 function url(path:string){return supabase?.storage.from("product-images").getPublicUrl(path).data.publicUrl??""}
 async function saveAlt(item:Media,value:string){if(!supabase)return;setSaving(item.id);const {error}=await supabase.from("media").update({alt_text:value.trim()||null}).eq("id",item.id);if(error)setError(error.message);else setItems(x=>x.map(m=>m.id===item.id?{...m,alt_text:value}:m));setSaving(null)}
 async function remove(item:Media){if(!supabase||item.product_images?.length||homepageMedia.has(item.id))return;if(!confirm("Энэ ашиглагдаагүй зургийг бүрмөсөн устгах уу?"))return;setSaving(item.id);setError("");const {error:de}=await supabase.from("media").delete().eq("id",item.id);if(de){setError(de.message);setSaving(null);return}setItems(x=>x.filter(m=>m.id!==item.id));const {error:se}=await supabase.storage.from("product-images").remove([item.storage_path]);if(se)setError("Медиа бүртгэл устсан боловч файл хадгалах сангаас устсангүй.");setSaving(null)}
 const shown=useMemo(()=>items.filter(i=>(i.filename+" "+(i.alt_text??"")+" "+(i.product_images?.map(p=>p.products?.name).join(" ")??"")).toLowerCase().includes(query.toLowerCase())),[items,query]);
 return <main className="admin-content"><div className="admin-page-head"><div><p className="admin-kicker">MEIRO / ADMIN</p><h1>Медиа</h1><p>Зураг, тайлбар болон ашиглалтыг удирдана.</p></div><div className="admin-media-count">{items.length} зураг</div></div>
 {error&&<p className="admin-error admin-message">{error}</p>}<div className="admin-media-toolbar"><input type="search" placeholder="Зураг хайх…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{items.filter(i=>!i.product_images?.length&&!homepageMedia.has(i.id)).length} ашиглагдаагүй</span></div>
 <div className="admin-media-grid">{shown.map(item=>{const productUses=item.product_images?.length??0;const onHomepage=homepageMedia.has(item.id);const used=productUses+(onHomepage?1:0);return <article className="admin-media-card" key={item.id}><div className="admin-media-preview"><img src={url(item.storage_path)} alt={item.alt_text||item.filename}/><span className={used?"used":"unused"}>{used?used+" газар ашигласан":"Ашиглагдаагүй"}</span></div><div className="admin-media-info"><strong title={item.filename}>{item.filename}</strong>{used>0&&<small>{item.product_images.map(p=><span key={p.id}>{p.products?.internal_reference||"—"} · {p.products?.name||"Бүтээгдэхүүн"}</span>)}{onHomepage&&<span>Нүүр хуудас · Carousel</span>}</small>}<label>Alt text<input defaultValue={item.alt_text??""} onBlur={e=>{if(e.target.value!==(item.alt_text??""))saveAlt(item,e.target.value)}}/></label><div className="admin-media-meta"><span>{item.mime_type?.replace("image/","").toUpperCase()||"IMAGE"}</span>{item.file_size!=null&&<span>{Math.max(1,Math.round(item.file_size/1024))} KB</span>}</div>{used===0&&<button type="button" className="admin-danger admin-media-delete" disabled={saving===item.id} onClick={()=>remove(item)}>{saving===item.id?"Устгаж байна…":"Устгах"}</button>}</div></article>})}</div>{shown.length===0&&<p className="admin-state">Зураг олдсонгүй.</p>}</main>
}