import { useEffect, useState } from "react";
import { supabase } from "../services/supabase";
type Media={id:string;storage_path:string;filename:string;alt_text:string|null};
type Slide={id:string;media_id:string;display_order:number;active:boolean;media:Media|null};
export default function AdminHome(){
 const [slides,setSlides]=useState<Slide[]>([]),[library,setLibrary]=useState<Media[]>([]),[error,setError]=useState("");
 async function load(){if(!supabase)return;const [{data:s,error},{data:m}]=await Promise.all([supabase.from("homepage_carousel").select("id,media_id,display_order,active,media(id,storage_path,filename,alt_text)").order("display_order"),supabase.from("media").select("id,storage_path,filename,alt_text").order("created_at",{ascending:false})]);if(error)setError(error.message);else setSlides((s??[]) as unknown as Slide[]);setLibrary((m??[]) as Media[])}
 useEffect(()=>{load()},[]);
 const url=(p:string)=>supabase?.storage.from("product-images").getPublicUrl(p).data.publicUrl??"";
 async function add(media_id:string){if(!supabase)return;const {error}=await supabase.from("homepage_carousel").insert({media_id,display_order:slides.length,active:true});if(error)setError(error.message);else await load()}
 async function remove(id:string){if(!supabase)return;const {error}=await supabase.from("homepage_carousel").delete().eq("id",id);if(error)setError(error.message);else await load()}
 async function toggle(s:Slide){if(!supabase)return;const {error}=await supabase.from("homepage_carousel").update({active:!s.active}).eq("id",s.id);if(error)setError(error.message);else setSlides(x=>x.map(v=>v.id===s.id?{...v,active:!v.active}:v))}
 async function move(index:number,d:number){if(!supabase)return;const j=index+d;if(j<0||j>=slides.length)return;const next=[...slides];[next[index],next[j]]=[next[j],next[index]];setSlides(next);for(let i=0;i<next.length;i++){const {error}=await supabase.from("homepage_carousel").update({display_order:i}).eq("id",next[i].id);if(error){setError(error.message);return}}}
 const available=library.filter(m=>!slides.some(s=>s.media_id===m.id));
 return <main className="admin-content"><div className="admin-page-head"><div><p className="admin-kicker">MEIRO / ADMIN</p><h1>Нүүр хуудас</h1><p>Нүүр хуудасны carousel зургийг сонгож, дарааллыг удирдана.</p></div></div>{error&&<p className="admin-error admin-message">{error}</p>}
 <section className="admin-panel"><h2>Carousel</h2>{slides.length===0?<p className="admin-empty">Зураг сонгоогүй байна.</p>:<div className="admin-home-slides">{slides.map((s,i)=><article key={s.id}><img src={s.media?url(s.media.storage_path):""} alt={s.media?.alt_text||""}/><div><strong>{s.media?.filename}</strong><span>{i+1}</span></div><div className="admin-home-slide-actions"><button type="button" disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button type="button" disabled={i===slides.length-1} onClick={()=>move(i,1)}>↓</button><button type="button" onClick={()=>toggle(s)}>{s.active?"Идэвхтэй":"Идэвхгүй"}</button><button type="button" className="admin-danger" onClick={()=>remove(s.id)}>Хасах</button></div></article>)}</div>}</section>
 <section className="admin-panel"><h2>Медиагаас нэмэх</h2><div className="admin-home-library">{available.map(m=><button type="button" key={m.id} onClick={()=>add(m.id)}><img src={url(m.storage_path)} alt={m.alt_text||m.filename}/><span>{m.filename}</span></button>)}</div>{available.length===0&&<p className="admin-empty">Нэмэх зураг алга байна.</p>}</section></main>
}